# joker docker-compose-gke.yml
# Used to create the joker docker image which will be deployed to Google GKE
# with kubernetes.

version: '3.1'

services:

  joker:
    container_name: joker
    image: us.gcr.io/kubedemo-233218/joker/joker
    build:
      context: .
      dockerfile: /Users/barry/go/src/github.com/bburch01/joker/Dockerfile
    ports:
      - "5000:5000"
               
